name: tarcisio
version: '1.0'
summary: Portfólio
description: |
  Aplicações de Tarcísio Deschamps.

grade: stable
confinement: strict
parts:
  webapp-container:
    plugin: nil    
    after: [desktop-ubuntu-app-platform, webapp-helper]
plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: false
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform
apps:
  tarcisio:
    command: webapp-launcher  --webappUrlPatterns=http://tdex.github.io/tarcisiodeschamps.com.br/* http://tdex.github.io/tarcisiodeschamps.com.br/
    # --enable-back-forward  (exibe botão de voltar no app)
    plugs:
      - browser-sandbox
      - network
      - opengl
      - unity7